### ISSUE TITLE
Partial argument match of 'len' to 'length.out'

### ISSUE THREAD

**Issue by fkohrt** [dmurdoch/tables#28]
Running the following [code from the README](https://github.com/dmurdoch/tables/blob/19a1901f30c88d78bbe4297ce2e352cd5342a347/README.Rmd#L47-L70) after setting the options as follows results in a warning about a "partial argument match of 'len' to 'length.out'":

```r
options(warnPartialMatchArgs = TRUE,
        warnPartialMatchDollar = TRUE,
        warnPartialMatchAttr = TRUE,
        warn = 2,
        lifecycle_verbosity = "error")
```

```r
library(tables)
set.seed(123)
table_options(htmloptions(head=FALSE))
X <- rnorm(125, sd=100)
Group <- factor(sample(letters[1:5], 125, replace=TRUE))
tab <- tabular( Group ~ 
                  (N=1) +
                  Format(digits=2)*X*
                  ((Mean=mean) +
                     Heading("Std Dev")*sd) 
)
tab
```

```
Error in rep(justification, len = length(x)) : 
  (converted from warning) partial argument match of 'len' to 'length.out'
```

The responsible line was identified upstream (at vincentarelbundock/modelsummary#804) as

https://github.com/dmurdoch/tables/blob/376e4041d0f9c777f052346596513579ee654853/R/tabular.R#L709

**Comment by dmurdoch** [comment]
Thanks.  There are a few other spots where I used `len` instead of `length.out`; I'll fix all of them.

**Comment by fkohrt** [comment]
Awesome, thanks! The code in the README also uses `rep` rather than `replace` as argument to `sample()`, could be edited in one go :)

https://github.com/dmurdoch/tables/blob/19a1901f30c88d78bbe4297ce2e352cd5342a347/README.Rmd#L58

**Comment by dmurdoch** [comment]
This change is in `tables` 0.9.31, which has just been accepted on CRAN.
